import type { AgentResult, StepLog } from "./types";

/* ── Simulated step sequence ── */
export const MOCK_STEPS: Omit<StepLog, "status">[] = [
  { id: "boot",     message: "> CALCIFER.EXE v1.0.0 — warming up" },
  { id: "parse",    message: "> Parsing GitHub coordinates...",        sub: "→ owner: facebook · repo: react" },
  { id: "meta",     message: "> Fetching repository metadata...",      sub: "→ Checking for life signs in the API..." },
  { id: "tree",     message: "> Scanning file system...",              sub: "→ Found 2,847 artifacts across 41 directories" },
  { id: "files",    message: "> Reading key files...",                 sub: "→ package.json, README.md, src/index.js, src/ReactDOM.js..." },
  { id: "ai",       message: "> Consulting the AI oracle...",          sub: "→ Asking Gemini to be useful (fingers crossed)" },
  { id: "weave",    message: "> Weaving documentation threads...",     sub: "→ Synthesizing 14 module insights" },
  { id: "assemble", message: "> Assembling sacred texts...",           sub: "→ Binding the tome" },
  { id: "done",     message: "> Done. Light the torches.",             sub: "→ Report ready in 0.98s" },
];

/* ── Mock markdown output ── */
export const MOCK_OUTPUT = `# facebook/react — Architecture Guide

## Overview

React is a declarative, component-based JavaScript library for building user interfaces. This guide maps the internals so you can contribute without losing your mind.

## Tech Stack

| Layer         | Technology                        |
|---------------|-----------------------------------|
| Language      | JavaScript / Flow types            |
| Build         | Rollup, Metro (for React Native)  |
| Test runner   | Jest + Testing Library            |
| Package mgmt  | Yarn (workspaces)                 |

## Repository Structure

React is a **monorepo** managed with Yarn workspaces. Key packages live under \`packages/\`:

\`\`\`
packages/
├── react/              Core React API (createElement, hooks, context)
├── react-dom/          Web renderer
├── react-reconciler/   Reconciler (shared between renderers)
├── scheduler/          Cooperative scheduling
├── react-devtools/     Browser DevTools
└── shared/             Utilities shared across packages
\`\`\`

## Core Architecture

React separates **what to render** (React elements) from **how to render** (renderers). The reconciler is renderer-agnostic — react-dom, react-native, and react-three-fiber all sit on top of it.

The modern architecture is called **Fiber** — a linked-list-based reconciliation engine that enables async rendering, priorities, and Suspense.

## Entry Points (Start Here)

1. \`packages/react/src/React.js\` — the public API surface
2. \`packages/react-reconciler/src/ReactFiber.js\` — the Fiber node definition
3. \`packages/react-dom/src/client/ReactDOMRoot.js\` — \`createRoot\` entry point
4. \`packages/scheduler/src/Scheduler.js\` — the task scheduler

## Good First Issues

- \`[bug]\` labels in the \`react\` package often have reproduction steps
- Documentation improvements in \`packages/react/\` — mostly JSDoc
- Adding test coverage for edge cases in hooks (useEffect, useMemo)

## Getting Started

\`\`\`bash
git clone https://github.com/facebook/react
cd react
yarn
yarn build react/cjs  # build just the core package
yarn test             # run the full suite (~3 min)
\`\`\`

> **Heads up:** The repo uses Flow for type checking (not TypeScript). Don't panic — just run \`yarn flow\` when you change typed files.

## Contributing Patterns

- PRs under 300 lines get reviewed fastest
- Every change needs a test in \`__tests__/\`
- Changelog entries live in \`.changeset/\`

---

*Generated by Calcifer · github.com/facebook/react*
`;

/* ── Mock result ── */
export const MOCK_RESULT: AgentResult = {
  metadata: {
    owner: "facebook",
    repo: "react",
    description: "The library for web and native user interfaces.",
    language: "JavaScript",
    stars: 228_000,
    openIssues: 748,
    url: "https://github.com/facebook/react",
  },
  output: MOCK_OUTPUT,
  mode: "documentation",
};
