"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { DraggableWindow } from "./DraggableWindow";
import { FireAnimation } from "./FireAnimation";
import type { AgentResult, AnalysisMode } from "@/app/lib/types";

interface OutputViewProps {
  result: AgentResult;
  onReset: () => void;
  onClose?: () => void;
  onMinimize?: () => void;
}

const MODE_LABEL: Record<AnalysisMode, string> = {
  documentation: "FULL DOCS",
  contribution: "CONTRIB GUIDE",
  bugs: "BUG HUNT",
};

export function OutputView({ result, onReset, onClose, onMinimize }: OutputViewProps) {
  const [copied, setCopied] = useState(false);

  const { metadata, output, mode } = result;

  function handleDownload() {
    const blob = new Blob([output], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${metadata.owner}-${metadata.repo}-${mode}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  async function handleCopy() {
    await navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <DraggableWindow
      title="MISSION_COMPLETE.MD"
      defaultWidth={720}
      onClose={onClose ?? onReset}
      onMinimize={onMinimize}
      headerRight={
        <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
          <RepoStats metadata={metadata} />
        </div>
      }
    >
      {/* Sub-header: fire + title + action buttons */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: "10px",
          padding: "14px 20px",
          borderBottom: "1px solid var(--color-ember-ash)",
          flexShrink: 0,
        }}
      >
        <FireAnimation width={36} height={36} className="animate-flicker" />
        <div style={{ flex: 1 }}>
          <h2
            style={{
              color: "var(--color-ember-amber)",
              fontSize: "0.8rem",
              fontWeight: 700,
              letterSpacing: "0.18em",
              textTransform: "uppercase",
            }}
          >
            CALCIFER
          </h2>
          <p style={{ color: "var(--color-ember-muted)", fontSize: "11px", marginTop: "2px" }}>
            {metadata.owner}/{metadata.repo} &middot;{" "}
            <span
              style={{
                color: "var(--color-ember-orange)",
                fontWeight: 600,
                letterSpacing: "0.06em",
              }}
            >
              {MODE_LABEL[mode]}
            </span>
          </p>
        </div>
        <div style={{ display: "flex", gap: "8px", flexShrink: 0 }}>
          <button className="btn-ghost btn-ghost--sm" onClick={handleCopy}>
            {copied ? "✓ Copied" : "Copy"}
          </button>
          <button className="btn-ghost btn-ghost--sm" onClick={handleDownload}>
            Download .md
          </button>
        </div>
      </div>

      {/* Markdown content — scrolls within .dw-content */}
      <div style={{ padding: "28px 28px 24px" }}>
        <div className="md-output">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>{output}</ReactMarkdown>
        </div>
      </div>

      {/* Footer */}
      <div
        style={{
          borderTop: "1px solid var(--color-ember-ash)",
          background: "var(--color-ember-surface)",
          padding: "12px 20px",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          flexShrink: 0,
        }}
      >
        <button className="btn-ghost btn-ghost--sm" onClick={onReset}>
          ← New mission
        </button>
        <span
          style={{
            color: "var(--color-ember-dim)",
            fontSize: "10px",
            letterSpacing: "0.06em",
          }}
        >
          Generated by Calcifer &middot; your key, your data
        </span>
      </div>
    </DraggableWindow>
  );
}

/* ── Compact repo stats badge ── */
function RepoStats({ metadata }: { metadata: AgentResult["metadata"] }) {
  return (
    <div
      style={{
        display: "flex",
        gap: "10px",
        fontSize: "10px",
        color: "var(--color-ember-muted)",
        letterSpacing: "0.04em",
      }}
    >
      {metadata.language && (
        <span style={{ color: "var(--color-ember-dim)" }}>{metadata.language}</span>
      )}
      <span>⭐ {metadata.stars.toLocaleString()}</span>
      <span>{metadata.openIssues.toLocaleString()} issues</span>
    </div>
  );
}
