"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { RetroWindow } from "./RetroWindow";
import { FireAnimation } from "./FireAnimation";
import type { AgentResult, AnalysisMode } from "@/app/lib/types";

interface OutputViewProps {
  result: AgentResult;
  onReset: () => void;
}

const MODE_LABEL: Record<AnalysisMode, string> = {
  documentation: "FULL DOCS",
  contribution: "CONTRIB GUIDE",
  bugs: "BUG HUNT",
};

export function OutputView({ result, onReset }: OutputViewProps) {
  const [copied, setCopied] = useState(false);

  const { metadata, output, mode } = result;

  function handleDownload() {
    const blob = new Blob([output], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${metadata.owner}-${metadata.repo}-${mode}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  async function handleCopy() {
    await navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div
      style={{
        minHeight: "100vh",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "flex-start",
        padding: "32px 16px 64px",
      }}
    >
      {/* Header */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: "10px",
          marginBottom: "24px",
          alignSelf: "flex-start",
          maxWidth: "720px",
          width: "100%",
          margin: "0 auto 24px",
        }}
      >
        <FireAnimation width={36} height={36} className="animate-flicker" />
        <div style={{ flex: 1 }}>
          <h2
            style={{
              color: "var(--color-ember-amber)",
              fontSize: "0.8rem",
              fontWeight: 700,
              letterSpacing: "0.18em",
              textTransform: "uppercase",
            }}
          >
            EMBERCORE
          </h2>
          <p
            style={{
              color: "var(--color-ember-muted)",
              fontSize: "11px",
              marginTop: "2px",
            }}
          >
            {metadata.owner}/{metadata.repo} &middot;{" "}
            <span
              style={{
                color: "var(--color-ember-orange)",
                fontWeight: 600,
                letterSpacing: "0.06em",
              }}
            >
              {MODE_LABEL[mode]}
            </span>
          </p>
        </div>

        {/* Actions */}
        <div style={{ display: "flex", gap: "8px", flexShrink: 0 }}>
          <button className="btn-ghost btn-ghost--sm" onClick={handleCopy}>
            {copied ? "✓ Copied" : "Copy"}
          </button>
          <button className="btn-ghost btn-ghost--sm" onClick={handleDownload}>
            Download .md
          </button>
        </div>
      </div>

      {/* Output Window */}
      <RetroWindow
        title="MISSION_COMPLETE.MD"
        style={{ width: "100%", maxWidth: "720px" }}
        headerRight={
          <div style={{ display: "flex", gap: "8px", alignItems: "center" }}>
            <RepoStats metadata={metadata} />
          </div>
        }
      >
        <div
          style={{
            padding: "28px 28px 24px",
            overflowY: "auto",
            maxHeight: "70vh",
          }}
        >
          <div className="md-output">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{output}</ReactMarkdown>
          </div>
        </div>

        {/* Footer */}
        <div
          style={{
            borderTop: "1px solid var(--color-ember-ash)",
            background: "var(--color-ember-surface)",
            padding: "12px 20px",
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
          }}
        >
          <button
            className="btn-ghost btn-ghost--sm"
            onClick={onReset}
          >
            ← New mission
          </button>

          <span
            style={{
              color: "var(--color-ember-dim)",
              fontSize: "10px",
              letterSpacing: "0.06em",
            }}
          >
            Generated by Embercore &middot; your key, your data
          </span>
        </div>
      </RetroWindow>
    </div>
  );
}

/* ── Compact repo stats badge ── */
function RepoStats({ metadata }: { metadata: AgentResult["metadata"] }) {
  return (
    <div
      style={{
        display: "flex",
        gap: "10px",
        fontSize: "10px",
        color: "var(--color-ember-muted)",
        letterSpacing: "0.04em",
      }}
    >
      {metadata.language && (
        <span style={{ color: "var(--color-ember-dim)" }}>
          {metadata.language}
        </span>
      )}
      <span>⭐ {metadata.stars.toLocaleString()}</span>
      <span>{metadata.openIssues.toLocaleString()} issues</span>
    </div>
  );
}
